[package]
name = "load-keypair"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-sdk = "2.2.0"
bs58 = "0.5.0"
dotenv = "0.15.0"
env = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"